{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"NfinityCloudError","kind":"identifier"}]}]}],"abstract":[{"text":"Represents an enum hierarchy for errors related to the Nfinity Cloud.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/attemptExceeded","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudHTTPError(httpCode:response:)","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/httpDeserialization(httpCode:cause:headers:)","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)"]},{"identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/Error-Implementations"],"title":"Default Implementations","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError"},"metadata":{"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","title":"NfinityCloudError","externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO","modules":[{"name":"PasswordAndNfinityFramework"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NfinityCloudError","kind":"identifier"}],"navigatorTitle":[{"text":"NfinityCloudError","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s5ErrorP","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror"]}],"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/s8SendableP":{"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/cloudError(errorCode:errorMessage:)":{"title":"NfinityCloudError.cloudError(errorCode:errorMessage:)","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cloudError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"errorCode"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"errorMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/clouderror(errorcode:errormessage:)","abstract":[{"text":"Represents an error with a specific error code and message that the Nfinity Cloud might return, but not from network call.","type":"text"}],"kind":"symbol"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfinityCloudError","kind":"identifier"}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","type":"topic","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the Nfinity Cloud."}],"title":"NfinityCloudError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfinityCloudError"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/s5ErrorP":{"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"title":"PasswordAndNfinityFramework","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/passwordandnfinityframework"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/cloudHTTPError(httpCode:response:)":{"type":"topic","abstract":[{"type":"text","text":"Represents an HTTP error from the Nfinity Cloud with the associated HTTP status code and a custom response object."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudHTTPError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"httpCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:27PasswordAndNfinityFramework0C18CloudErrorResponseV","text":"NfinityCloudErrorResponse","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/cloudhttperror(httpcode:response:)","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudHTTPError(httpCode:response:)","kind":"symbol","title":"NfinityCloudError.cloudHTTPError(httpCode:response:)"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/attemptExceeded":{"type":"topic","abstract":[{"text":"Case represents too many tries on ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionSender\/sendFaceDetection(imageData:)","type":"reference"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attemptExceeded"}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/attemptexceeded","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/attemptExceeded","kind":"symbol","title":"NfinityCloudError.attemptExceeded"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/httpDeserialization(httpCode:cause:headers:)":{"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/httpdeserialization(httpcode:cause:headers:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"httpDeserialization"},{"text":"(","kind":"text"},{"text":"httpCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"cause","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headers"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Indicates a problem with deserializing the HTTP response into a model object."}],"kind":"symbol","title":"NfinityCloudError.httpDeserialization(httpCode:cause:headers:)","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/httpDeserialization(httpCode:cause:headers:)"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/Error-Implementations":{"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/error-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article","title":"Error Implementations","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/Error-Implementations"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/FaceDetectionSender/sendFaceDetection(imageData:)":{"url":"\/documentation\/passwordandnfinityframework\/facedetectionsender\/sendfacedetection(imagedata:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendFaceDetection","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageData"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> Swift"},{"kind":"text","text":"."},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"FaceDetectionState","preciseIdentifier":"s:27PasswordAndNfinityFramework18FaceDetectionStateO"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"NfinityCloudError","preciseIdentifier":"s:27PasswordAndNfinityFramework0C10CloudErrorO"},{"text":">","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Method for sending face detection data, and returns an "},{"type":"codeVoice","code":"Swift.Result"},{"type":"text","text":" instance."}],"kind":"symbol","title":"sendFaceDetection(imageData:)","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionSender\/sendFaceDetection(imageData:)"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/network(cause:)":{"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO","text":"CommunicatorError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Case represents network error"}],"kind":"symbol","title":"NfinityCloudError.network(cause:)","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)"}}}