{"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the Nfinity Cloud."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s5ErrorP","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfinityCloudError"}]}]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfinityCloudError"}],"title":"NfinityCloudError","externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfinityCloudError"}],"modules":[{"name":"PasswordAndNfinityFramework"}],"roleHeading":"Enumeration","symbolKind":"enum"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/attemptExceeded","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudHTTPError(httpCode:response:)","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/httpDeserialization(httpCode:cause:headers:)","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/Error-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror"]}],"kind":"symbol","references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/network(cause:)":{"abstract":[{"type":"text","text":"Case represents network error"}],"title":"NfinityCloudError.network(cause:)","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommunicatorError","kind":"typeIdentifier","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/FaceDetectionSender/sendFaceDetection(imageData:)":{"title":"sendFaceDetection(imageData:)","abstract":[{"text":"Method for sending face detection data, and returns an ","type":"text"},{"type":"codeVoice","code":"Swift.Result"},{"type":"text","text":" instance."}],"url":"\/documentation\/passwordandnfinityframework\/facedetectionsender\/sendfacedetection(imagedata:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionSender\/sendFaceDetection(imageData:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFaceDetection"},{"kind":"text","text":"("},{"text":"imageData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"FaceDetectionState","kind":"typeIdentifier","preciseIdentifier":"s:27PasswordAndNfinityFramework18FaceDetectionStateO"},{"text":", ","kind":"text"},{"text":"NfinityCloudError","kind":"typeIdentifier","preciseIdentifier":"s:27PasswordAndNfinityFramework0C10CloudErrorO"},{"text":">","kind":"text"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/cloudHTTPError(httpCode:response:)":{"abstract":[{"type":"text","text":"Represents an HTTP error from the Nfinity Cloud with the associated HTTP status code and a custom response object."}],"title":"NfinityCloudError.cloudHTTPError(httpCode:response:)","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/cloudhttperror(httpcode:response:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudHTTPError(httpCode:response:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudHTTPError","kind":"identifier"},{"kind":"text","text":"("},{"text":"httpCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"response","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NfinityCloudErrorResponse","kind":"typeIdentifier","preciseIdentifier":"s:27PasswordAndNfinityFramework0C18CloudErrorResponseV"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/Error-Implementations":{"title":"Error Implementations","abstract":[],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/error-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/Error-Implementations","type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"abstract":[{"text":"Represents an enum hierarchy for errors related to the Nfinity Cloud.","type":"text"}],"title":"NfinityCloudError","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","role":"symbol","navigatorTitle":[{"text":"NfinityCloudError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfinityCloudError","kind":"identifier"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"kind":"symbol","url":"\/documentation\/passwordandnfinityframework","role":"collection","title":"PasswordAndNfinityFramework","abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/attemptExceeded":{"title":"NfinityCloudError.attemptExceeded","abstract":[{"type":"text","text":"Case represents too many tries on "},{"isActive":true,"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/FaceDetectionSender\/sendFaceDetection(imageData:)","type":"reference"},{"type":"text","text":"."}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/attemptexceeded","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/attemptExceeded","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attemptExceeded"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s8SendableP"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/cloudError(errorCode:errorMessage:)":{"title":"NfinityCloudError.cloudError(errorCode:errorMessage:)","abstract":[{"type":"text","text":"Represents an error with a specific error code and message that the Nfinity Cloud might return, but not from network call."}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/clouderror(errorcode:errormessage:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cloudError","kind":"identifier"},{"kind":"text","text":"("},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"errorMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/httpDeserialization(httpCode:cause:headers:)":{"abstract":[{"type":"text","text":"Indicates a problem with deserializing the HTTP response into a model object."}],"title":"NfinityCloudError.httpDeserialization(httpCode:cause:headers:)","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/httpdeserialization(httpcode:cause:headers:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/httpDeserialization(httpCode:cause:headers:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"httpDeserialization","kind":"identifier"},{"kind":"text","text":"("},{"text":"httpCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cause","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/s5ErrorP"}}}