{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Represents an error with a specific error code and message that the Nfinity Cloud might return, but not from network call."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror\/clouderror(errorcode:errormessage:)"]}],"metadata":{"title":"NfinityCloudError.cloudError(errorCode:errorMessage:)","symbolKind":"case","role":"symbol","roleHeading":"Case","externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO05cloudF0yACSSSg_AEtcACmF","modules":[{"name":"PasswordAndNfinityFramework"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudError"},{"kind":"text","text":"("},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"errorMessage"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError"]]},"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudError"},{"kind":"text","text":"("},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorMessage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"errorCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional error code as a string, that helps identify the type of error."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An optional human-readable message providing more details about the error.","type":"text"}]}],"name":"errorMessage"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"title":"PasswordAndNfinityFramework","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","url":"\/documentation\/passwordandnfinityframework","type":"topic","abstract":[],"kind":"symbol","role":"collection"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"kind":"symbol","navigatorTitle":[{"text":"NfinityCloudError","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","type":"topic","role":"symbol","abstract":[{"text":"Represents an enum hierarchy for errors related to the NfinityÂ Cloud.","type":"text"}],"title":"NfinityCloudError","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfinityCloudError","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/cloudError(errorCode:errorMessage:)":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudError"},{"kind":"text","text":"("},{"text":"errorCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorMessage"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/clouderror(errorcode:errormessage:)","role":"symbol","title":"NfinityCloudError.cloudError(errorCode:errorMessage:)","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","kind":"symbol","abstract":[{"type":"text","text":"Represents an error with a specific error code and message that the Nfinity Cloud might return, but not from network call."}]}}}