{"sections":[],"abstract":[{"text":"Case represents network error","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"PasswordAndNfinityFramework"}],"role":"symbol","symbolKind":"case","title":"NfinityCloudError.network(cause:)","externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO7networkyAC012CommunicatorD00hF0O_tcACmF","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cause"},{"kind":"text","text":": "},{"text":"CommunicatorError","kind":"typeIdentifier","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)"]}],"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cause","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO","text":"CommunicatorError","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/network(cause:)":{"abstract":[{"type":"text","text":"Case represents network error"}],"role":"symbol","kind":"symbol","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)","title":"NfinityCloudError.network(cause:)","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cause"},{"kind":"text","text":": "},{"text":"CommunicatorError","kind":"typeIdentifier","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO"},{"text":")","kind":"text"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"abstract":[{"text":"Represents an enum hierarchy for errors related to the NfinityÂ Cloud.","type":"text"}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfinityCloudError","kind":"identifier"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","navigatorTitle":[{"kind":"identifier","text":"NfinityCloudError"}],"kind":"symbol","type":"topic","role":"symbol","title":"NfinityCloudError"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"abstract":[],"url":"\/documentation\/passwordandnfinityframework","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","title":"PasswordAndNfinityFramework","role":"collection","type":"topic","kind":"symbol"}}}