{"metadata":{"externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO7networkyAC012CommunicatorD00hF0O_tcACmF","symbolKind":"case","roleHeading":"Case","title":"NfinityCloudError.network(cause:)","modules":[{"name":"PasswordAndNfinityFramework"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cause"},{"text":": ","kind":"text"},{"text":"CommunicatorError","kind":"typeIdentifier","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO"},{"kind":"text","text":")"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Case represents network error","type":"text"}],"variants":[{"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO","text":"CommunicatorError","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"navigatorTitle":[{"text":"NfinityCloudError","kind":"identifier"}],"type":"topic","role":"symbol","title":"NfinityCloudError","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the NfinityÂ Cloud."}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfinityCloudError"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/network(cause:)":{"role":"symbol","title":"NfinityCloudError.network(cause:)","abstract":[{"type":"text","text":"Case represents network error"}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CommunicatorError","kind":"typeIdentifier","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO"},{"text":")","kind":"text"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"abstract":[],"role":"collection","url":"\/documentation\/passwordandnfinityframework","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","type":"topic","title":"PasswordAndNfinityFramework"}}}