{"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Case","title":"NfinityCloudError.cloudError(errorCode:errorMessage:)","externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO05cloudF0yACSSSg_AEtcACmF","symbolKind":"case","modules":[{"name":"PasswordAndNfinityFramework"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cloudError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"errorCode"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"errorMessage"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Represents an error with a specific error code and message that the Nfinity Cloud might return, but not from network call.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cloudError"},{"kind":"text","text":"("},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"errorMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An optional error code as a string, that helps identify the type of error."}],"type":"paragraph"}],"name":"errorCode"},{"name":"errorMessage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional human-readable message providing more details about the error."}]}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror\/clouderror(errorcode:errormessage:)"]}],"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"url":"\/documentation\/passwordandnfinityframework","title":"PasswordAndNfinityFramework","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","kind":"symbol"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"type":"topic","abstract":[{"type":"text","text":"Represents an enum hierarchy for errors related to the NfinityÂ Cloud."}],"title":"NfinityCloudError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfinityCloudError"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","kind":"symbol","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","role":"symbol","navigatorTitle":[{"text":"NfinityCloudError","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/cloudError(errorCode:errorMessage:)":{"role":"symbol","type":"topic","title":"NfinityCloudError.cloudError(errorCode:errorMessage:)","kind":"symbol","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/cloudError(errorCode:errorMessage:)","abstract":[{"type":"text","text":"Represents an error with a specific error code and message that the Nfinity Cloud might return, but not from network call."}],"url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/clouderror(errorcode:errormessage:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cloudError"},{"text":"(","kind":"text"},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"errorMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}]}}}