{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"network","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cause"},{"kind":"text","text":": "},{"text":"CommunicatorError","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError"]]},"sections":[],"metadata":{"modules":[{"name":"PasswordAndNfinityFramework"}],"title":"NfinityCloudError.network(cause:)","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"network","kind":"identifier"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO","text":"CommunicatorError","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"case","externalID":"s:27PasswordAndNfinityFramework0C10CloudErrorO7networkyAC012CommunicatorD00hF0O_tcACmF"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Case represents network error","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)"]}],"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError/network(cause:)":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"network"},{"kind":"text","text":"("},{"text":"cause","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CommunicatorError","kind":"typeIdentifier","preciseIdentifier":"s:21CommunicatorFramework0A5ErrorO"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError\/network(cause:)","title":"NfinityCloudError.network(cause:)","abstract":[{"text":"Case represents network error","type":"text"}],"kind":"symbol","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror\/network(cause:)","role":"symbol"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudError":{"abstract":[{"text":"Represents an enum hierarchy for errors related to the NfinityÂ Cloud.","type":"text"}],"role":"symbol","kind":"symbol","title":"NfinityCloudError","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"NfinityCloudError","kind":"identifier"}],"type":"topic","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderror","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudError","navigatorTitle":[{"text":"NfinityCloudError","kind":"identifier"}]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"role":"collection","title":"PasswordAndNfinityFramework","type":"topic","url":"\/documentation\/passwordandnfinityframework","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework"}}}