{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/passwordandnfinityframework\/nfinityclouderrorresponse\/exception"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"exception","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudErrorResponse\/exception","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudErrorResponse"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"exception","modules":[{"name":"PasswordAndNfinityFramework"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"exception","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"s:27PasswordAndNfinityFramework0C18CloudErrorResponseV9exceptionSSSgvp"},"sections":[],"references":{"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework":{"title":"PasswordAndNfinityFramework","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework","type":"topic","role":"collection","url":"\/documentation\/passwordandnfinityframework","kind":"symbol","abstract":[]},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudErrorResponse":{"abstract":[],"identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudErrorResponse","kind":"symbol","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderrorresponse","title":"NfinityCloudErrorResponse","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfinityCloudErrorResponse"}],"navigatorTitle":[{"kind":"identifier","text":"NfinityCloudErrorResponse"}],"type":"topic"},"doc://com.aheaditec.widgetizing.PasswordAndNfinityFramework/documentation/PasswordAndNfinityFramework/NfinityCloudErrorResponse/exception":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"exception","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","title":"exception","url":"\/documentation\/passwordandnfinityframework\/nfinityclouderrorresponse\/exception","identifier":"doc:\/\/com.aheaditec.widgetizing.PasswordAndNfinityFramework\/documentation\/PasswordAndNfinityFramework\/NfinityCloudErrorResponse\/exception","abstract":[],"type":"topic"}}}